### PR TITLE
Ask if the user wants to change the labyrinth type instead of disabling the option

### PR DESCRIPTION
**Pull request by markojaadam**
Solution for Issue #36

### CODE REVIEW

**Comment by krajcsi** [comment]
I guess there's no need for the 'change' variable. Simply move the redraw part to the then branch of the Warning dialog.

**Comment by markojaadam** [comment]
Updated with a new commit.

**Comment by krajcsi** [comment]
Oh, I see. Then instead of using 'change', check if we are in stop mode to change the labyrinth type (the confirmation dialog will change it if needed). I.e., change is only True iff we are in stop mode, so they mean the same things. (If I didn't miss some essential part again.)

**Comment by krajcsi** [comment]
OK, in the meantime you just did that ;)

**Comment by markojaadam** [comment]
Felülírjam még gyorsan a mostani 1.1 verziót, vagy ez már egy új 
verzióba menjen bele?

Üdv,
Ádám


2017-04-08 14:14 keltezéssel, krajcsi írta:

**Pull request merged**
